import Link from "next/link";
import { BrainCircuit, Database, Scale, ShieldCheck, UserCheck } from "lucide-react";
import { MarketingNav } from "@/components/marketing-nav";

const controls = [
  [UserCheck, "Human decisions", "AI can suggest wording and a next action, but a person reviews communications and decides whether to act or escalate."],
  [BrainCircuit, "Visible AI assistance", "AI-generated recommendations and reply analysis are labelled, explainable and treated as support—not fact or legal advice."],
  [Database, "Data rights support", "Signed-in users can export workspace data and record access, correction, restriction, objection or erasure requests."],
  [ShieldCheck, "Traceable collection work", "Approvals, exports, rights requests and collection activity are recorded in the workspace audit trail."],
] as const;

export default function CompliancePage() {
  return <main className="min-h-screen bg-[#F7F9FC]"><div className="bg-white"><MarketingNav /></div><section className="px-5 py-14 sm:px-8"><div className="mx-auto max-w-5xl"><p className="eyebrow">Europe-ready foundation</p><h1 className="mt-3 max-w-3xl text-4xl font-bold tracking-tight text-ink sm:text-5xl">Practical privacy, AI transparency and human control.</h1><p className="mt-5 max-w-3xl text-lg leading-8 text-slate-600">CreditPilot is being built as a credit-control system of action for UK and European teams. This centre explains the operational safeguards in the current beta. It is not a certification or a substitute for legal advice.</p>
    <div className="mt-10 grid gap-5 sm:grid-cols-2">{controls.map(([Icon, title, copy]) => <article key={title} className="rounded-xl border border-slate-100 bg-white p-6 shadow-card"><Icon className="text-electric" size={24} /><h2 className="mt-4 font-bold text-ink">{title}</h2><p className="mt-2 text-sm leading-6 text-slate-600">{copy}</p></article>)}</div>
    <section className="mt-10 rounded-xl border border-blue-100 bg-white p-7 shadow-card"><div className="flex items-start gap-3"><Scale className="mt-1 text-electric" size={22} /><div><h2 className="text-xl font-bold text-ink">Who is responsible for the data?</h2><p className="mt-2 leading-7 text-slate-600">Your organisation normally decides why and how customer, invoice and collection data is used, making it the controller. CreditPilot processes that workspace data to provide the service. CreditPilot separately determines how account, security, billing and service-administration data is used. The exact role always depends on the processing context.</p></div></div></section>
    <section className="mt-8 rounded-xl border border-slate-100 bg-white p-7 shadow-card"><h2 className="text-xl font-bold text-ink">Current data map</h2><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[640px] text-left text-sm"><thead><tr className="border-b text-slate-500"><th className="pb-3 pr-5">Data</th><th className="pb-3 pr-5">Purpose</th><th className="pb-3">Control</th></tr></thead><tbody className="divide-y text-slate-700"><Row data="Account and company" purpose="Authentication, workspace and support" control="Access-controlled; export and request tools" /><Row data="Customers and invoices" purpose="Prioritisation and collection workflow" control="Company-scoped records; your ledger stays authoritative" /><Row data="Reminders and replies" purpose="Prepare and record communications" control="Draft, review and approval before sending" /><Row data="Promises, disputes and actions" purpose="Track commitments and ownership" control="Timeline and audit history" /><Row data="AI prompts and outputs" purpose="Suggested wording and next actions" control="Labelled assistance; human decision required" /></tbody></table></div></section>
    <section className="mt-8 grid gap-5 md:grid-cols-2"><Info title="Lawful use">Customers remain responsible for identifying and documenting an appropriate lawful basis for their collection activity, supplying privacy information and respecting objections. Consent is not assumed to be the only available basis.</Info><Info title="Rights and response handling">The workspace supports access, correction, restriction, objection, portability and erasure workflows. Requests should be verified, recorded and answered without undue delay; legal retention exceptions may apply.</Info><Info title="Retention and deletion">Keep personal data only as long as needed for the collection purpose, contract, legal duties or claims. Account deletion is reviewed so required financial and audit records are not removed improperly.</Info><Info title="Providers and transfers">The service uses specialist hosting, database, email, payment and AI providers as needed. Provider terms, processing locations and lawful transfer safeguards must be reviewed before expanding European availability.</Info><Info title="Electronic communications">Users must apply the privacy and electronic-marketing rules that govern their recipient and message. CreditPilot records approvals but does not make a communication lawful by itself.</Info><Info title="Security and incidents">The service uses authenticated, company-scoped access, password hashing, private exports, audit records and protective browser headers. Security controls and incident procedures require continuing review as the beta grows.</Info></section>
    <div className="mt-10 rounded-xl bg-ink p-7 text-white"><h2 className="text-xl font-bold">Use the controls</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-blue-100">Workspace users can download their data or record a privacy request in Settings. People appearing in a customer&apos;s CreditPilot records should normally contact that customer organisation first as controller.</p><div className="mt-5 flex flex-wrap gap-3"><Link className="button-primary" href="/settings">Open privacy settings</Link><Link className="rounded-lg border border-white/30 px-4 py-2.5 text-sm font-semibold" href="/privacy">Read the Privacy Notice</Link></div></div>
  </div></section></main>;
}

function Row({ data, purpose, control }: { data: string; purpose: string; control: string }) { return <tr><td className="py-4 pr-5 font-semibold text-ink">{data}</td><td className="py-4 pr-5">{purpose}</td><td className="py-4">{control}</td></tr>; }
function Info({ title, children }: { title: string; children: React.ReactNode }) { return <article className="rounded-xl border border-slate-100 bg-white p-6 shadow-card"><h2 className="font-bold text-ink">{title}</h2><p className="mt-2 text-sm leading-6 text-slate-600">{children}</p></article>; }
