import { redirect } from "next/navigation";
import { auth } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { DashboardSidebar } from "@/components/dashboard-sidebar";
import { askCopilot, analyseCustomerReply } from "./actions";
export const dynamic = "force-dynamic";
export default async function CopilotPage({ searchParams }: { searchParams: Promise<{ answer?: string; question?: string; error?: string; replyResult?: string }> }) {
  const session = await auth(); if (!session?.user?.email) redirect("/login");
  const user = await prisma.user.findUnique({ where: { email: session.user.email } }); if (!user) redirect("/login");
  const params = await searchParams;
  return <main className="flex min-h-screen"><DashboardSidebar /><div className="min-w-0 flex-1"><header className="border-b bg-white px-5 py-4 sm:px-8"><p className="text-sm text-slate-500">Owner dashboard</p><h1 className="text-xl font-bold text-ink">CreditPilot Copilot</h1></header><div className="mx-auto max-w-3xl space-y-6 p-5 sm:p-8"><section className="rounded-xl border bg-white p-6 shadow-card"><h2 className="text-2xl font-bold text-ink">Ask a question</h2><p className="mt-2 text-slate-600">Ask about your invoices, customers, payments, or reminders.</p><form action={askCopilot} className="mt-6 flex gap-3"><input name="question" required defaultValue={params.question} placeholder="Who owes me the most?" className="flex-1 rounded-lg border px-3 py-3" /><button className="button-primary" type="submit">Ask Copilot</button></form>{params.answer && <div className="mt-6 rounded-lg bg-sky p-5"><p className="text-sm font-semibold text-electric">Copilot answer</p><p className="mt-2 whitespace-pre-line text-slate-700">{params.answer}</p></div>}<div className="mt-6 text-sm text-slate-500">Try: Which invoices are overdue? or Who should I chase today?</div></section><section className="rounded-xl border bg-white p-6 shadow-card"><h2 className="text-xl font-bold text-ink">Analyse a customer reply</h2><p className="mt-2 text-slate-600">Paste a customer email to identify the intent and get the next best action.</p><form action={analyseCustomerReply} className="mt-5 space-y-3"><textarea name="reply" required rows={5} placeholder="Example: We will pay the invoice on Friday. Sorry for the delay." className="w-full rounded-lg border px-3 py-3" /><button className="button-primary" type="submit">Analyse reply</button></form>{params.replyResult && <div className="mt-5 rounded-lg bg-sky p-5"><p className="text-sm font-semibold text-electric">Reply analysis</p><p className="mt-2 whitespace-pre-line text-slate-700">{params.replyResult}</p></div>}</section></div></div></main>;
}