import Link from "next/link";
import { ArrowLeft, CheckCircle2 } from "lucide-react";
import { redirect } from "next/navigation";
import { auth } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { DashboardSidebar } from "@/components/dashboard-sidebar";
import { markInvoicePaid } from "./actions";
export const dynamic = "force-dynamic";
export default async function PaymentsPage({ searchParams }: { searchParams: Promise<{ paid?: string }> }) { const session = await auth(); if (!session?.user?.email) redirect("/login"); const user = await prisma.user.findUnique({ where: { email: session.user.email } }); if (!user) redirect("/login"); const invoices = await prisma.invoice.findMany({ where: { companyId: user.companyId, status: { not: "PAID" } }, include: { customer: true }, orderBy: { dueDate: "asc" } }); const params = await searchParams; return <main className="flex min-h-screen"><DashboardSidebar /><div className="min-w-0 flex-1"><header className="border-b bg-white px-5 py-4 sm:px-8"><p className="text-sm text-slate-500">Credit control workspace</p><h1 className="text-xl font-bold tracking-tight text-ink">Payments</h1></header><div className="mx-auto max-w-5xl p-5 sm:p-8"><Link href="/dashboard" className="mb-6 inline-flex items-center gap-2 text-sm font-semibold text-slate-500 hover:text-electric"><ArrowLeft size={16} />Back to dashboard</Link>{params.paid && <p className="mb-5 rounded-lg bg-emerald-50 p-3 text-sm font-semibold text-emerald-700">Invoice marked as paid. It will no longer appear on statements.</p>}<section className="overflow-hidden rounded-xl border border-slate-100 bg-white shadow-card"><div className="border-b p-5"><h2 className="font-bold text-ink">Outstanding invoices</h2><p className="mt-1 text-sm text-slate-500">Mark invoices as paid when payment arrives.</p></div>{invoices.length === 0 ? <p className="p-8 text-sm text-slate-500">No outstanding invoices.</p> : <div className="divide-y">{invoices.map((invoice) => <div key={invoice.id} className="flex items-center justify-between gap-4 p-5"><div><p className="font-semibold text-ink">{invoice.number} · {invoice.customer.name}</p><p className="mt-1 text-sm text-slate-500">Due {invoice.dueDate.toLocaleDateString("en-GB")} · £{Number(invoice.amount).toLocaleString("en-GB", { minimumFractionDigits: 2 })}</p></div><form action={markInvoicePaid}><input type="hidden" name="invoiceId" value={invoice.id} /><button className="button-secondary" type="submit"><CheckCircle2 size={16} className="mr-2" />Mark paid</button></form></div>)}</div>}</section></div></div></main>; }
