import Link from "next/link";
import { MarketingNav } from "@/components/marketing-nav";

export default function PrivacyPage() {
  return <main className="min-h-screen bg-[#F7F9FC]"><div className="bg-white"><MarketingNav /></div><div className="mx-auto max-w-3xl px-5 py-10 sm:px-8"><article className="rounded-2xl border bg-white p-7 shadow-card sm:p-10"><p className="eyebrow">Legal</p><h1 className="mt-2 text-3xl font-bold text-ink">Privacy Notice</h1><p className="mt-2 text-sm text-slate-500">Last updated: 27 August 2026</p><p className="mt-6 leading-7 text-slate-700">This notice explains how CreditPilot AI handles personal information in its credit-control system of action. It covers account users and people whose contact or collection information is held in a customer workspace.</p>
    <Section title="1. Our role">A subscribing business normally controls the customer, invoice and collection data it uploads. CreditPilot provides the service and processes that data on its instructions. CreditPilot is separately responsible for account administration, security, support, billing and service operation. Roles may vary with the facts.</Section>
    <Section title="2. Information handled">We may handle names, business contact details, account credentials, company settings, invoice details, payment status, communications, promises to pay, disputes, workflow actions, audit events, support information and technical security records. We do not ask users to upload special-category data unless it is genuinely necessary and lawful.</Section>
    <Section title="3. Purposes and lawful grounds">Information is used to authenticate users, operate and secure workspaces, organise collection work, prepare user-approved communications, provide support, administer the beta and meet legal duties. Depending on the activity, processing may rely on contract, legitimate interests, legal obligation or consent where consent is required. Customer organisations must determine and document the basis for their own collection activity.</Section>
    <Section title="4. AI-assisted features">CreditPilot may use AI to suggest priorities, wording, classifications or next actions. These outputs are assistance, may be incomplete and require human review. CreditPilot does not use them to make or execute solely automated legal, credit or enforcement decisions about a person.</Section>
    <Section title="5. Sharing and international transfers">Information is shared only as needed with providers supporting hosting, databases, email, payments, security, support and optional AI functions, or where law requires it. Where personal data is transferred internationally, appropriate contractual or other recognised safeguards should be used and kept under review.</Section>
    <Section title="6. Retention and deletion">Information is kept only for as long as needed for the service, the collection purpose, security, legal obligations, dispute resolution or legal claims. Retention can vary by record and customer instruction. Account deletion requests are reviewed before removal because some financial or audit records may lawfully need to be retained.</Section>
    <Section title="7. Your rights">Depending on the applicable UK or EU law and circumstances, you may request access, correction, erasure, restriction, portability or object to processing. You may also complain to the relevant supervisory authority. We may verify identity and will explain if a request cannot be fulfilled in full.</Section>
    <Section title="8. How to make a request">Signed-in users can download workspace data and record a request in Settings. If your details appear in another business&apos;s workspace, contact that business first because it normally controls the record; CreditPilot will support verified requests from it. Requests should be answered without undue delay and normally within the applicable statutory period.</Section>
    <Section title="9. Security and cookies">We use access controls, password hashing, company-scoped queries, private downloads, audit logging and protective browser headers. No system is risk-free. See our <Link className="font-semibold text-electric" href="/cookies">Cookie Notice</Link> for essential session cookies.</Section>
    <Section title="10. Changes">We may update this notice as the service, providers and European availability develop. Material changes will be communicated through an appropriate channel.</Section>
    <p className="mt-8 border-t pt-6 text-sm leading-6 text-slate-500">This notice documents the current beta controls; it is not a compliance certification. Company identity, contact details, provider contracts, retention periods and transfer arrangements must be confirmed with a qualified UK/EU privacy professional before full commercial launch.</p>
  </article></div></main>;
}
function Section({ title, children }: { title: string; children: React.ReactNode }) { return <section className="mt-7"><h2 className="text-lg font-bold text-ink">{title}</h2><p className="mt-2 leading-7 text-slate-700">{children}</p></section>; }
