import { BarChart3, Bell, Bot, Building2, ClipboardList, CreditCard, FileText, LayoutDashboard, MessageSquareText, Scale, Settings, Users, ShieldCheck, LifeBuoy } from "lucide-react";
import Link from "next/link";
import { auth } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { Logo } from "./logo";
import { LogoutButton } from "./logout-button";

const links = [[LayoutDashboard, "Dashboard", "/dashboard"], [Users, "Customers", "/customers"], [MessageSquareText, "Communication history", "/communications"], [FileText, "Invoices", "/invoices"], [Bell, "Reminders", "/reminders"], [ClipboardList, "Collections", "/collections"], [ClipboardList, "Statements", "/statements"], [ClipboardList, "Payments", "/payments"], [Bot, "CreditPilot Copilot", "/copilot"], [BarChart3, "Reports", "/reports"], [CreditCard, "Membership", "/pricing"], [Settings, "Settings", "/settings"], [LifeBuoy, "Report a problem", "/support"], [Scale, "Terms", "/terms"], [ShieldCheck, "Privacy", "/privacy"]] as const;

export async function DashboardSidebar() { const session = await auth(); const platformAdmin = session?.user?.email ? await prisma.user.findUnique({ where: { email: session.user.email }, select: { isPlatformAdmin: true } }) : null; return <aside className="hidden min-h-screen w-64 shrink-0 border-r border-slate-200 bg-white p-5 lg:flex lg:flex-col"><Logo href="/dashboard" /><div className="mt-10 space-y-1">{links.map(([Icon, label, href], index) => <Link href={href} key={label} className={`flex w-full items-center gap-3 rounded-lg px-3 py-2.5 text-left text-sm font-medium ${index === 0 ? "bg-sky text-electric" : "text-slate-600 hover:bg-slate-50"}`}><Icon size={18} />{label}</Link>)}{platformAdmin?.isPlatformAdmin && <Link href="/admin" className="flex w-full items-center gap-3 rounded-lg bg-violet-50 px-3 py-2.5 text-left text-sm font-semibold text-violet-700 hover:bg-violet-100"><Building2 size={18} />Platform Admin</Link>}</div><div className="mt-2"><LogoutButton /></div><div className="mt-auto rounded-xl bg-ink p-4 text-white"><p className="text-sm font-semibold">Need a hand?</p><p className="mt-1 text-xs leading-5 text-blue-100">Ask CreditPilot Copilot for your next best action.</p></div></aside>; }
