import Link from "next/link";
import { MarketingNav } from "@/components/marketing-nav";

export default function TermsPage() {
  return <main className="min-h-screen bg-[#F7F9FC]"><div className="bg-white"><MarketingNav /></div><div className="mx-auto max-w-3xl px-5 py-10 sm:px-8"><article className="rounded-2xl border bg-white p-7 shadow-card sm:p-10"><p className="eyebrow">Legal</p><h1 className="mt-2 text-3xl font-bold text-ink">Terms and Conditions</h1><p className="mt-2 text-sm text-slate-500">Last updated: 27 August 2026</p><p className="mt-6 leading-7 text-slate-700">These terms govern the CreditPilot AI beta, a dedicated credit-control workflow service that works alongside accounting software. By creating an account or using the service, you agree to them.</p>
    <Section title="1. The service">CreditPilot organises imported invoice data, priorities, recommended actions, reminders, promises, disputes and collection history. It is not accounting software, a credit-reference agency, debt collection agency or legal adviser, and does not guarantee payment.</Section>
    <Section title="2. Human control and AI">AI-assisted output may be inaccurate or incomplete. You must review every recommendation and communication before relying on or sending it. CreditPilot does not independently decide whether to grant credit, enforce a debt or begin legal action.</Section>
    <Section title="3. Your responsibilities">You are responsible for accurate data, lawful collection activity, an appropriate data-protection basis, required privacy information, communication rules, recipient objections and the authority to upload data. Do not use the service for harassment, discrimination, unlawful profiling or misleading communications.</Section>
    <Section title="4. Communications">Drafts and timing suggestions remain under user control. You are responsible for tone, recipients, frequency and legal compliance. Delivery may be affected by recipient systems, provider outages or spam controls.</Section>
    <Section title="5. Data, exports and deletion">Your accounting platform remains the system of record. You should keep appropriate backups and reconcile material changes. Workspace exports and privacy requests are available in Settings. Deletion may be limited where records must be retained for law, security, tax or legal claims.</Section>
    <Section title="6. Security and access">Keep credentials secure, use the service only through authorised accounts and notify us promptly of suspected compromise. We may restrict access needed to protect users, data or the service.</Section>
    <Section title="7. Beta, integrations and availability">Features may change during beta. CSV import is current; Xero, QuickBooks and Sage connections are roadmap items until explicitly released. The service is provided as available and may be suspended for maintenance, security or provider disruption.</Section>
    <Section title="8. Plans and cancellation">Current beta access is free unless the Membership page says otherwise. Paid terms, taxes, renewal and cancellation details will be shown before a charge is accepted.</Section>
    <Section title="9. Liability">To the extent permitted by law, CreditPilot is not responsible for indirect losses, customer non-payment or decisions made from unverified data or AI output. Nothing excludes liability that cannot legally be excluded.</Section>
    <Section title="10. Changes and law">We may update these terms as the beta develops and will publish the current version here. The governing law, contracting entity, address and dispute route must be confirmed in the final commercial terms.</Section>
    <p className="mt-8 border-t pt-6 text-sm leading-6 text-slate-500">These beta terms are transparent working terms, not a substitute for signed commercial terms. They require review by a qualified solicitor before accepting paying UK or European customers.</p>
  </article></div></main>;
}
function Section({ title, children }: { title: string; children: React.ReactNode }) { return <section className="mt-7"><h2 className="text-lg font-bold text-ink">{title}</h2><p className="mt-2 leading-7 text-slate-700">{children}</p></section>; }
