import Link from "next/link";
import { ArrowLeft, Settings as SettingsIcon } from "lucide-react";
import { redirect } from "next/navigation";
import { auth } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { DashboardSidebar } from "@/components/dashboard-sidebar";
import { saveCompanySettings } from "./actions";
export const dynamic = "force-dynamic";
export default async function SettingsPage({ searchParams }: { searchParams: Promise<{ saved?: string; error?: string }> }) { const session = await auth(); if (!session?.user?.email) redirect("/login"); const user = await prisma.user.findUnique({ where: { email: session.user.email }, include: { company: true } }); if (!user) redirect("/login"); const params = await searchParams; return <main className="flex min-h-screen"><DashboardSidebar /><div className="min-w-0 flex-1"><header className="border-b bg-white px-5 py-4 sm:px-8"><p className="text-sm text-slate-500">Credit control workspace</p><h1 className="text-xl font-bold tracking-tight text-ink">Settings</h1></header><div className="mx-auto max-w-4xl p-5 sm:p-8"><Link href="/dashboard" className="mb-6 inline-flex items-center gap-2 text-sm font-semibold text-slate-500 hover:text-electric"><ArrowLeft size={16} />Back to dashboard</Link>{params.saved && <p className="mb-5 rounded-lg bg-emerald-50 p-3 text-sm font-semibold text-emerald-700">Settings saved.</p>}{params.error && <p className="mb-5 rounded-lg bg-rose-50 p-3 text-sm font-semibold text-rose-700">Please enter a company name.</p>}<section className="rounded-xl border border-slate-100 bg-white p-6 shadow-card"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-lg bg-sky text-electric"><SettingsIcon size={20} /></span><div><h2 className="font-bold text-ink">Company profile</h2><p className="text-sm text-slate-500">These details are used in statements and emails.</p></div></div><form action={saveCompanySettings} className="mt-5 space-y-4"><Field name="name" label="Company name" value={user.company.name} /><Field name="billingEmail" label="Billing email" value={user.company.billingEmail || user.email} type="email" /><button className="button-primary" type="submit">Save settings</button></form></section><section className="mt-6 rounded-xl border border-slate-100 bg-white p-6 shadow-card"><h2 className="font-bold text-ink">Reminder rules</h2><p className="mt-1 text-sm text-slate-500">7 days before due · 1 day before due · 7, 8 and 15 days overdue.</p></section></div></div></main>; }
function Field({ name, label, value, type = "text" }: { name: string; label: string; value: string; type?: string }) { return <label className="block text-sm font-medium text-slate-700">{label}<input name={name} type={type} defaultValue={value} className="mt-1.5 w-full rounded-lg border px-3 py-2.5 outline-none focus:border-electric" /></label>; }
