import Link from "next/link";
import { ArrowLeft } from "lucide-react";
import { redirect } from "next/navigation";
import { auth } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { DashboardSidebar } from "@/components/dashboard-sidebar";
import { saveCompanySettings } from "./actions";
export const dynamic = "force-dynamic";
export default async function SettingsPage({ searchParams }: { searchParams: Promise<{ saved?: string; error?: string }> }) { const session = await auth(); if (!session?.user?.email) redirect("/login"); const user = await prisma.user.findUnique({ where: { email: session.user.email }, include: { company: true } }); if (!user) redirect("/login"); const params = await searchParams; return <main className="flex min-h-screen"><DashboardSidebar /><div className="min-w-0 flex-1"><header className="border-b bg-white px-5 py-4 sm:px-8"><p className="text-sm text-slate-500">Credit control workspace</p><h1 className="text-xl font-bold tracking-tight text-ink">Settings</h1></header><div className="mx-auto max-w-4xl p-5 sm:p-8"><Link href="/dashboard" className="mb-6 inline-flex items-center gap-2 text-sm font-semibold text-slate-500"><ArrowLeft size={16} />Back to dashboard</Link>{params.saved && <p className="mb-5 rounded-lg bg-emerald-50 p-3 text-sm font-semibold text-emerald-700">Settings saved.</p>}<section className="rounded-xl border border-slate-100 bg-white p-6 shadow-card"><h2 className="font-bold text-ink">Profile and company</h2><p className="mt-1 text-sm text-slate-500">Your name appears in the dashboard greeting and customer emails.</p><form action={saveCompanySettings} className="mt-5 space-y-4"><Field name="personalName" label="Your name" value={user.name || ""} placeholder="Peter Ingham" /><Field name="name" label="Company name" value={user.company.name} placeholder="Your company" /><Field name="billingEmail" label="Billing email" value={user.company.billingEmail || user.email} placeholder="accounts@company.co.uk" type="email" /><button className="button-primary" type="submit">Save settings</button></form></section></div></div></main>; }
function Field({ name, label, value, placeholder, type = "text" }: { name: string; label: string; value: string; placeholder: string; type?: string }) { return <label className="block text-sm font-medium text-slate-700">{label}<input name={name} type={type} defaultValue={value} placeholder={placeholder} required className="mt-1.5 w-full rounded-lg border px-3 py-2.5 outline-none focus:border-electric" /></label>; }
