import { ArrowLeft, LifeBuoy } from "lucide-react";
import Link from "next/link";
import { DashboardSidebar } from "@/components/dashboard-sidebar";
import { submitSupportRequest } from "./actions";

export default async function SupportPage({ searchParams }: { searchParams: Promise<{ sent?: string; error?: string }> }) {
  const params = await searchParams;
  return <main className="flex min-h-screen"><DashboardSidebar /><div className="min-w-0 flex-1"><header className="border-b bg-white px-5 py-4 sm:px-8"><p className="text-sm text-slate-500">CreditPilot AI support</p><h1 className="text-xl font-bold tracking-tight text-ink">Report a problem</h1></header><div className="mx-auto max-w-3xl p-5 sm:p-8"><Link href="/dashboard" className="mb-6 inline-flex items-center gap-2 text-sm font-semibold text-slate-500 hover:text-electric"><ArrowLeft size={16} />Back to dashboard</Link><section className="rounded-xl border border-slate-100 bg-white p-6 shadow-card"><div className="flex items-start gap-3"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-lg bg-sky text-electric"><LifeBuoy size={20} /></span><div><h2 className="font-bold text-ink">Need help?</h2><p className="mt-1 text-sm leading-6 text-slate-600">Tell us what went wrong and we’ll get back to you. Your account details are included automatically.</p></div></div>{params.sent === "1" && <p className="mt-5 rounded-lg bg-emerald-50 p-3 text-sm font-semibold text-emerald-700">Your report has been sent. We’ll be in touch soon.</p>}{params.error && <p className="mt-5 rounded-lg bg-rose-50 p-3 text-sm font-semibold text-rose-700">{params.error === "description" ? "Please describe the problem in a little more detail." : params.error === "email-not-configured" ? "Support email is not configured yet. Please contact your workspace owner." : "We could not send your report. Please try again."}</p>}<form action={submitSupportRequest} className="mt-6 space-y-5"><label className="block text-sm font-medium text-slate-700">What does this relate to?<select name="category" className="mt-1.5 w-full rounded-lg border bg-white px-3 py-3"><option>Login or account access</option><option>Customers</option><option>Invoices</option><option>Reminders or email</option><option>Payments</option><option>Something else</option></select></label><label className="block text-sm font-medium text-slate-700">Describe the problem<textarea name="description" required minLength={10} rows={7} className="mt-1.5 w-full rounded-lg border px-3 py-3 outline-none focus:border-electric focus:ring-2 focus:ring-blue-100" placeholder="Tell us what happened, including any error message you saw." /></label><button className="button-primary" type="submit">Send report</button></form></section></div></div></main>;
}
